## ci/cd from source code
version: "3"

services:

  mayi-upms-biz:
    container_name: mayi-upms-biz
    restart: on-failure
    ports:
      - "7777:7777"
      - "5555:5555"
    build:
      context: ./
      dockerfile: docker/prod/system/Dockerfile
    image: mayi-upms-biz
    environment:
      NACOS_BASE_URL: mayi.nacos:8848
    depends_on:
      - mayi-nacos
      - mayi-mysql
      - mayi-redis
      - mayi-auth
      - mayi-visual-admin
      - mayi-gateway
    hostname: mayi.upms.biz

  mayi-auth:
    container_name: mayi-auth
    restart: on-failure
    ports:
      - "9000:9000"
      - "6666:6666"
    build:
      context: ./
      dockerfile: docker/prod/auth/Dockerfile
    image: mayi-auth
    environment:
      NACOS_BASE_URL: mayi.nacos:8848
    depends_on:
      - mayi-nacos
      - mayi-redis
      - mayi-mysql
      - mayi-visual-admin
      - mayi-gateway
    hostname: mayi.auth

  mayi-gateway:
    container_name: mayi-gateway
    restart: on-failure
    ports:
      - "8888:8888"
    build:
      context: ./
      dockerfile: docker/prod/gateway/Dockerfile
    image: mayi-gateway
    environment:
      NACOS_BASE_URL: mayi.nacos:8848
    depends_on:
      - mayi-nacos
      - mayi-redis
    hostname: mayi.gateway

  mayi-visual-admin:
    container_name: mayi-visual-admin
    restart: on-failure
    ports:
      - "4444:4444"
    build:
      context: ./
      dockerfile: docker/prod/monitor/Dockerfile
    image: mayi-visual-admin
    hostname: mayi.visual.admin

  mayi-redis:
    container_name: mayi-redis
    image: redis:6.2.6
    restart: on-failure
    ports:
      - "6379:6379"
    hostname: mayi.redis

  mayi-mysql:
    container_name: mayi-mysql
    build:
      context: ./
      dockerfile: ./docker/db/Dockerfile
    restart: on-failure
    env_file:
      - ./env/.mysql_env
      - ./env/.nacos_env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-itcast}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-nacos}
      MYSQL_USER: ${MYSQL_USER:-nacos}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-nacos}
    security_opt:
      - seccomp:unconfined
    image: mayi-mysql
    ports:
      - "3306:3306"
    hostname: mayi.mysql

  mayi-nacos:
    container_name: mayi-nacos
    image: nacos/nacos-server
    restart: on-failure
    env_file:
      - ./env/.nacos_env
      - ./env/.mysql_env
    environment:
      JVM_XMX: 256m
      JVM_XMS: 256m
      JVM_XMN: 192m
      MODE: standalone
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_DATABASE_NUM: 1
      MYSQL_SERVICE_HOST: mayi.mysql
      MYSQL_SERVICE_PORT: ${MYSQL_PORT:-3306}
      MYSQL_SERVICE_USER: ${MYSQL_USER:-nacos}
      MYSQL_SERVICE_PASSWORD: ${MYSQL_PASSWORD:-nacos}
      MYSQL_SERVICE_DB_NAME: ${MYSQL_DATABASE:-nacos}
      MYSQL_SERVICE_DB_PARAM: ${MYSQL_SERVICE_DB_PARAM:-allowPublicKeyRetrieval=true&useSSL=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&serverTimezone=GMT%2B8}
    ports:
      - "8848:8848"
    depends_on:
      - mayi-mysql
    hostname: mayi.nacos
